language: node_js
node_js:
- 8.4.0
install: npm install
script: npm run build
cache:
  directories:
  - node_modules

before_deploy: "cp .gitignore-production .gitignore"

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master
